# Generated by Django 4.0.1 on 2022-01-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profiledoctor')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profilesick')),
            ],
        ),
    ]
